import gleam/int
import gleam/list
import gleam/string
import scherzo_lint/high_signal/inventory.{
  type CountRow, type Finding, type ModuleCountRow,
}

pub fn render_markdown(raw_findings: List(Finding)) -> String {
  let findings = inventory.sort_findings(raw_findings)
  let total = inventory.total_count_row(findings)

  "# Glinter high-signal warning baseline\n\n"
  <> "Generated by `direnv exec . gleam run -m scherzo_lint_high_signal_inventory -- --output docs/lint/glinter-high-signal-baseline.md`. "
  <> "Counts track `discarded_result`, `error_context_lost`, `stringly_typed_error`, `thrown_away_error`, and selected `unwrap_used` findings by subsystem and module.\n\n"
  <> "Total tracked findings: "
  <> int.to_string(total.total)
  <> "\n\n"
  <> "## Counts by rule\n\n"
  <> render_count_rows(inventory.rule_count_rows(findings), "Rule")
  <> "\n## Counts by subsystem\n\n"
  <> render_count_rows(inventory.subsystem_count_rows(findings), "Subsystem")
  <> "\n## Counts by module\n\n"
  <> render_module_rows(inventory.module_count_rows(findings))
}

fn render_count_rows(rows: List(CountRow), label: String) -> String {
  case rows {
    [] -> "_No findings._\n"
    _ -> {
      let body =
        rows
        |> list.map(fn(row) {
          "| "
          <> markdown_cell(row.group)
          <> " | "
          <> int.to_string(row.total)
          <> " | "
          <> int.to_string(row.discarded_result)
          <> " | "
          <> int.to_string(row.error_context_lost)
          <> " | "
          <> int.to_string(row.stringly_typed_error)
          <> " | "
          <> int.to_string(row.thrown_away_error)
          <> " | "
          <> int.to_string(row.unwrap_used)
          <> " |"
        })
        |> string.join("\n")

      "| "
      <> label
      <> " | Total | `discarded_result` | `error_context_lost` | `stringly_typed_error` | `thrown_away_error` | `unwrap_used` |\n"
      <> "| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n"
      <> body
      <> "\n"
    }
  }
}

fn render_module_rows(rows: List(ModuleCountRow)) -> String {
  case rows {
    [] -> "_No findings._\n"
    _ -> {
      let body =
        rows
        |> list.map(fn(row) {
          let counts = row.counts
          "| "
          <> markdown_cell(row.subsystem)
          <> " | `"
          <> row.module_name
          <> "` | "
          <> int.to_string(counts.total)
          <> " | "
          <> int.to_string(counts.discarded_result)
          <> " | "
          <> int.to_string(counts.error_context_lost)
          <> " | "
          <> int.to_string(counts.stringly_typed_error)
          <> " | "
          <> int.to_string(counts.thrown_away_error)
          <> " | "
          <> int.to_string(counts.unwrap_used)
          <> " |"
        })
        |> string.join("\n")

      "| Subsystem | Module | Total | `discarded_result` | `error_context_lost` | `stringly_typed_error` | `thrown_away_error` | `unwrap_used` |\n"
      <> "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |\n"
      <> body
      <> "\n"
    }
  }
}

fn markdown_cell(value: String) -> String {
  value
  |> string.replace(each: "|", with: "\\|")
  |> string.replace(each: "\n", with: " ")
}
