import gleam/dict.{type Dict}
import gleam/int
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import scherzo_lint/public_api_style/inventory.{type Finding}

pub fn render_markdown(raw_findings: List(Finding)) -> String {
  let findings = inventory.sort_findings(raw_findings)

  "# Scherzo public API style inventory\n\n"
  <> "Generated by `direnv exec . gleam run -m scherzo_lint_inventory`. Findings are inventory data, not lint failures.\n\n"
  <> "Total findings: "
  <> int.to_string(list.length(findings))
  <> "\n\n"
  <> "## Counts by candidate\n\n"
  <> render_count_table(count_by(findings, candidate_count_key))
  <> "\n## Counts by subsystem\n\n"
  <> render_count_table(count_by(findings, fn(finding) { finding.subsystem }))
  <> "\n## Counts by module\n\n"
  <> render_count_table(count_by(findings, fn(finding) { finding.module_name }))
  <> "\n## Counts by API shape\n\n"
  <> render_count_table(count_by(findings, fn(finding) { finding.api_shape }))
  <> "\n## Findings\n\n"
  <> render_findings_table(findings)
}

fn candidate_count_key(finding: Finding) -> String {
  inventory.candidate_name(finding.candidate)
}

fn render_count_table(rows: List(#(String, Int))) -> String {
  case rows {
    [] -> "_No findings._\n"
    _ -> {
      let body =
        rows
        |> list.sort(by: fn(left, right) { string.compare(left.0, right.0) })
        |> list.map(fn(row) {
          "| " <> markdown_cell(row.0) <> " | " <> int.to_string(row.1) <> " |"
        })
        |> string.join("\n")

      "| Group | Findings |\n" <> "| --- | ---: |\n" <> body <> "\n"
    }
  }
}

fn render_findings_table(findings: List(Finding)) -> String {
  case findings {
    [] -> "_No findings._\n"
    _ -> {
      let body =
        findings
        |> list.map(render_finding_row)
        |> string.join("\n")

      "| Candidate | Subsystem | Module | Path | Function | Arity | API shape | Primitive | Existing rule coverage | Likely exception | Churn estimate |\n"
      <> "| --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- | ---: |\n"
      <> body
      <> "\n"
    }
  }
}

fn render_finding_row(finding: Finding) -> String {
  "| "
  <> markdown_cell(inventory.candidate_name(finding.candidate))
  <> " | "
  <> markdown_cell(finding.subsystem)
  <> " | `"
  <> finding.module_name
  <> "` | `"
  <> finding.path
  <> "` | `"
  <> finding.function_name
  <> "` | "
  <> int.to_string(finding.arity)
  <> " | "
  <> markdown_cell(finding.api_shape)
  <> " | "
  <> markdown_cell(option_string(finding.primitive_type))
  <> " | "
  <> markdown_cell(bool_string(finding.covered_by_existing_rule))
  <> " | "
  <> markdown_cell(option_string(finding.likely_exception))
  <> " | "
  <> int.to_string(finding.estimated_callsite_churn)
  <> " |"
}

fn count_by(
  findings: List(Finding),
  key: fn(Finding) -> String,
) -> List(#(String, Int)) {
  findings
  |> list.fold(from: dict.new(), with: fn(counts, finding) {
    increment(counts, key(finding))
  })
  |> dict.to_list
}

fn increment(counts: Dict(String, Int), key: String) -> Dict(String, Int) {
  let count = case dict.get(counts, key) {
    Ok(current) -> current + 1
    Error(Nil) -> 1
  }

  dict.insert(counts, key, count)
}

fn option_string(value: Option(String)) -> String {
  case value {
    Some(text) -> text
    None -> ""
  }
}

fn bool_string(value: Bool) -> String {
  case value {
    True -> "yes"
    False -> "no"
  }
}

fn markdown_cell(value: String) -> String {
  value
  |> string.replace(each: "|", with: "\\|")
  |> string.replace(each: "\n", with: " ")
}
